#!/usr/bin/env python3
"""
gen-hook-manifest.py

Reads the tweak's own source and writes the list of external symbols it depends
on: every class it hooks, every method it hooks inside those classes, and every
class it resolves by name at runtime (%c / objc_getClass / NSClassFromString).

The output is a C file the debugger reads at launch to check each dependency
against the running app. Generated at build time, never edited by hand — a
hand-kept list drifts and then lies, which is exactly the failure it exists to
catch. Run from the repo root; the Makefile invokes it before compiling.

Deliberately conservative: only %hook blocks on real Objective-C classes are
treated as external. Methods added to the tweak's OWN classes live in
@implementation, not %hook, so they are never mistaken for hooks on Twitter.
"""

import os
import re
import sys

SRC = "src"
OUT = "src/Generated/NFBHookManifest.m"

# A %hook line names the class; everything up to the matching %end is its body.
HOOK_RE = re.compile(r'^\s*%hook\s+([A-Za-z_][A-Za-z0-9_$]*)\s*$')
END_RE = re.compile(r'^\s*%end\s*$')
# A method inside a hook body: - (ret)name...  or  + (ret)name...
# Only the first selector piece is taken; enough to look the method up.
METHOD_RE = re.compile(r'^\s*[-+]\s*\([^)]*\)\s*([A-Za-z_][A-Za-z0-9_]*)')
# Runtime class resolution, all three spellings the tweak uses.
BYNAME_RE = re.compile(
    r'%c\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)'
    r'|objc_getClass\(\s*"([A-Za-z_][A-Za-z0-9_.]*)"\s*\)'
    r'|NSClassFromString\(\s*@"([A-Za-z_][A-Za-z0-9_.]*)"\s*\)'
)


def source_files():
    for root, _dirs, files in os.walk(SRC):
        if "Generated" in root:
            continue
        for name in sorted(files):
            if name.endswith(".x") or name.endswith(".m"):
                yield os.path.join(root, name)


def parse():
    # class -> set of hooked methods (a class hooked with no method still counts)
    hooks = {}
    byname = set()
    # Classes the tweak DEFINES itself (via @interface … : Super). These are
    # loaded with the tweak, never part of Twitter, so a hook or a %c() on one
    # is not an external dependency and must not be health-checked against the
    # app's own classes. FLEX and Cephei classes are excluded the same way,
    # by prefix, since they too are injected rather than Twitter's.
    own_classes = set()
    own_prefixes = ("FLEX", "HBForce", "Cephei", "PS")
    interface_re = re.compile(r'^@interface\s+([A-Za-z_][A-Za-z0-9_]*)')

    for path in source_files():
        rel = os.path.relpath(path, SRC)
        with open(path, encoding="utf-8") as handle:
            lines = handle.readlines()
        for line in lines:
            match = interface_re.match(line)
            if match:
                own_classes.add(match.group(1))

    for path in source_files():
        rel = os.path.relpath(path, SRC)
        with open(path, encoding="utf-8") as handle:
            lines = handle.readlines()
        current = None
        pending_new = False  # the next method line is a %new, created by us
        for line in lines:
            stripped = line.split("//", 1)[0]  # ignore line comments
            hook = HOOK_RE.match(stripped)
            if hook:
                current = hook.group(1)
                hooks.setdefault(current, {"methods": set(), "file": rel})
                pending_new = False
                continue
            if END_RE.match(stripped):
                current = None
                pending_new = False
                continue
            # A %new anywhere on the line means the method that follows is added
            # by the tweak, not a Twitter dependency — never a missing hook.
            if "%new" in stripped:
                pending_new = True
                continue
            if current:
                method = METHOD_RE.match(stripped)
                if method:
                    if pending_new:
                        pending_new = False  # consumed by this method
                    else:
                        hooks[current]["methods"].add(method.group(1))
            for match in BYNAME_RE.finditer(stripped):
                name = match.group(1) or match.group(2) or match.group(3)
                if name:
                    byname.add(name)

    def is_own(name):
        return name in own_classes or name.startswith(own_prefixes)

    hooks = {cls: info for cls, info in hooks.items() if not is_own(cls)}
    byname = {name for name in byname if not is_own(name)}
    return hooks, byname


def escape(text):
    return text.replace("\\", "\\\\").replace('"', '\\"')


def emit(hooks, byname):
    lines = []
    lines.append("//")
    lines.append("//  NFBHookManifest.m — GENERATED by tools/gen-hook-manifest.py")
    lines.append("//  Do not edit. Regenerated on every build from the tweak's source.")
    lines.append("//")
    lines.append("")
    lines.append('#import "Generated/NFBHookManifest.h"')
    lines.append("")

    # Flattened method table: one row per (class, method), plus one row per
    # class with a NULL method so a class hooked with no method is still checked.
    lines.append("const NFBHookRecord NFBHookRecords[] = {")
    for cls in sorted(hooks):
        info = hooks[cls]
        file_literal = escape(info["file"])
        methods = sorted(info["methods"])
        if not methods:
            lines.append(
                '    {"%s", NULL, "%s"},' % (escape(cls), file_literal))
        else:
            for method in methods:
                lines.append(
                    '    {"%s", "%s", "%s"},'
                    % (escape(cls), escape(method), file_literal))
    lines.append("};")
    lines.append(
        "const size_t NFBHookRecordCount = "
        "sizeof(NFBHookRecords) / sizeof(NFBHookRecords[0]);")
    lines.append("")

    lines.append("const char* const NFBRuntimeClasses[] = {")
    for name in sorted(byname):
        lines.append('    "%s",' % escape(name))
    lines.append("};")
    lines.append(
        "const size_t NFBRuntimeClassCount = "
        "sizeof(NFBRuntimeClasses) / sizeof(NFBRuntimeClasses[0]);")
    lines.append("")
    return "\n".join(lines)


def emit_header():
    return """//
//  NFBHookManifest.h — GENERATED by tools/gen-hook-manifest.py
//  Do not edit.
//
#import <stddef.h>

typedef struct {
    const char* className;
    const char* methodName;  // NULL when the class is hooked with no method
    const char* file;
} NFBHookRecord;

extern const NFBHookRecord NFBHookRecords[];
extern const size_t NFBHookRecordCount;

extern const char* const NFBRuntimeClasses[];
extern const size_t NFBRuntimeClassCount;
"""


def main():
    if not os.path.isdir(SRC):
        sys.stderr.write("gen-hook-manifest: run from the repo root (no src/)\n")
        return 1
    hooks, byname = parse()
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(emit(hooks, byname))
    header = os.path.join(os.path.dirname(OUT), "NFBHookManifest.h")
    with open(header, "w", encoding="utf-8") as handle:
        handle.write(emit_header())

    method_rows = sum(
        len(info["methods"]) or 1 for info in hooks.values())
    sys.stderr.write(
        "gen-hook-manifest: %d classes, %d method rows, %d runtime classes\n"
        % (len(hooks), method_rows, len(byname)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
